[server]
port = 8506

[browser]
gatherUsageStats = false

[theme]
# Clean Grok-inspired Theme with White Background
primaryColor = "#4A5D23"          # OD Green for accent buttons
backgroundColor = "#FAFAFA"       # Clean light gray background
secondaryBackgroundColor = "#FFFFFF" # Pure white panels/cards
textColor = "#1A1A1A"             # Clean black text
font = "sans serif"              # Modern clean font style
